unit TestBinaryTree;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  {$IFDEF FPC}fpcunit, testutils, testregistry,
  {$ELSE}TestFramework,{$ENDIF}
  Classes, mBinaryTree;

type

  TTestBinaryTree = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSimpleTree;
  end;


implementation

uses
  SysUtils, Dialogs, Forms;


procedure TTestBinaryTree.SetUp;
begin
  inherited;
end;

procedure TTestBinaryTree.TearDown;
begin
  inherited;
end;

procedure TTestBinaryTree.TestSimpleTree;
var
  TempTree : TmBinTree;
begin
  TempTree := TmBinTree.Create;
  try
    //
  finally
    TempTree.Free;
  end;
end;

initialization
  Randomize;
  // Register any test cases with the test runner
  {$IFDEF FPC}
  RegisterTest(TTestBinaryTree);
  {$ELSE}
  RegisterTest(TTestBinaryTree.Suite);
  {$ENDIF}

end.

